// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: 실제 Web Firebase 프로젝트 설정으로 교체하세요.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'WEB_API_KEY',
    appId: '1:302365711592:web:WEB_APP_ID',
    messagingSenderId: '302365711592',
    projectId: 'clubal',
    storageBucket: 'clubal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPug7cNzIZvuIw0Mb5ny8CFCO42qgIUCk',
    appId: '1:302365711592:android:196d5fd693faf568313d5d',
    messagingSenderId: '302365711592',
    projectId: 'clubal',
    storageBucket: 'clubal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3BYODoWbR9wb9Zs2fzy5M-JDYV-oBUlY',
    appId: '1:302365711592:ios:ea4cc0528d1d9d47313d5d',
    messagingSenderId: '302365711592',
    projectId: 'clubal',
    storageBucket: 'clubal.firebasestorage.app',
    iosClientId:
        '302365711592-4mehvo94eivr9h67plpfc1nd4nr268uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubalApp',
  );
}
