import 'package:clubal_app/features/chat/models/chat_room.dart';
import 'package:clubal_app/features/chat/models/message.dart';

List<ChatRoom> createDummyRooms() {
  final now = DateTime.now();
  return [
    ChatRoom(
      id: 'room_group1',
      otherUserId: '',
      otherUserName: '강남 클럽 조각모임',
      name: '강남 클럽 조각모임',
      participants: [
        ChatParticipant(userId: 'user1', name: '강남불나방', imageUrl: 'https://picsum.photos/seed/a1/200', bio: '강남 클럽 자주 가요! 같이 놀아요~', gender: '남성'),
        ChatParticipant(userId: 'user2', name: '홍대병말기', imageUrl: 'https://picsum.photos/seed/b2/200', bio: '홍대 감성주점 좋아해요', gender: '여성'),
        ChatParticipant(userId: 'user3', name: '힙스터', imageUrl: null, bio: '이태원 힙합 클럽 매니아', gender: '남성'),
        ChatParticipant(userId: 'me', name: '나', imageUrl: null, bio: '저는 나입니다.', gender: '남성'),
      ],
      isGroup: true,
      groupImage: null,
      lastMessage: '내일 저녁 7시에 강남역에서 만나요!',
      lastMessageAt: now.subtract(const Duration(minutes: 5)),
      unreadCount: 3,
      isPinned: true,
      locationTag: '강남역 · Club Arena',
      meetingDate: now.add(const Duration(days: 1)),
    ),
    ChatRoom(
      id: 'room1',
      otherUserId: 'user1',
      otherUserName: '강남불나방',
      otherUserImageUrl: 'https://picsum.photos/seed/a1/200',
      lastMessage: '내일 저녁 7시에 강남역에서 만나요!',
      lastMessageAt: now.subtract(const Duration(minutes: 5)),
      unreadCount: 2,
      isOnline: true,
      participants: [
        ChatParticipant(userId: 'user1', name: '강남불나방', imageUrl: 'https://picsum.photos/seed/a1/200', bio: '강남 클럽 자주 가요! 같이 놀아요~', gender: '남성'),
      ],
    ),
    ChatRoom(
      id: 'room2',
      otherUserId: 'user2',
      otherUserName: '홍대병말기',
      otherUserImageUrl: 'https://picsum.photos/seed/b2/200',
      lastMessage: '[사진]',
      lastMessageAt: now.subtract(const Duration(hours: 2)),
      unreadCount: 0,
      participants: [
        ChatParticipant(userId: 'user2', name: '홍대병말기', imageUrl: 'https://picsum.photos/seed/b2/200', bio: '홍대 감성주점 좋아해요', gender: '여성'),
      ],
    ),
    ChatRoom(
      id: 'room3',
      otherUserId: 'user3',
      otherUserName: '힙스터',
      otherUserImageUrl: null,
      lastMessage: '이태원 클럽 어때요?',
      lastMessageAt: now.subtract(const Duration(days: 1)),
      unreadCount: 1,
      isOnline: true,
      participants: [
        ChatParticipant(userId: 'user3', name: '힙스터', imageUrl: null, bio: '이태원 힙합 클럽 매니아', gender: '남성'),
      ],
    ),
    ChatRoom(
      id: 'room4',
      otherUserId: 'user4',
      otherUserName: '클럽러버',
      otherUserImageUrl: 'https://picsum.photos/seed/c3/200',
      lastMessage: '이번 주말에 같이 가요!',
      lastMessageAt: now.subtract(const Duration(days: 2)),
      unreadCount: 0,
      isMuted: true,
      participants: [
        ChatParticipant(userId: 'user4', name: '클럽러버', imageUrl: 'https://picsum.photos/seed/c3/200', bio: '주말마다 클럽 다녀요', gender: '남성'),
      ],
    ),
  ];
}

Map<String, List<Message>> createDummyMessages() {
  final now = DateTime.now();
  return {
    'room_group1': [
      Message(
        id: 'sg1',
        type: MessageType.system,
        content: '강남불나방님이 방을 만들었습니다.',
        createdAt: now.subtract(const Duration(hours: 5)),
        isMe: false,
        isSystemMessage: true,
      ),
      Message(
        id: 'sg2',
        type: MessageType.system,
        content: '홍대병말기님이 방에 입장했습니다.',
        createdAt: now.subtract(const Duration(hours: 4)),
        isMe: false,
        isSystemMessage: true,
      ),
      Message(
        id: 'sg3',
        type: MessageType.system,
        content: '모임 시간이 2월 22일 19:00으로 변경되었습니다.',
        createdAt: now.subtract(const Duration(hours: 3)),
        isMe: false,
        isSystemMessage: true,
      ),
      Message(
        id: 'mg1',
        type: MessageType.text,
        text: '안녕하세요! 강남 클럽 조각 같이 가실 분 구해요.',
        senderId: 'user1',
        senderName: '강남불나방',
        content: '안녕하세요! 강남 클럽 조각 같이 가실 분 구해요.',
        createdAt: now.subtract(const Duration(hours: 3)),
        isMe: false,
      ),
      Message(
        id: 'mg2',
        type: MessageType.text,
        text: '저요! 몇 명 모이면 되나요?',
        senderId: 'me',
        senderName: '나',
        content: '저요! 몇 명 모이면 되나요?',
        createdAt: now.subtract(const Duration(hours: 2, minutes: 55)),
        isMe: true,
        isRead: true,
      ),
      Message(
        id: 'mg3',
        type: MessageType.text,
        text: '4명이요. 지금 2명 있어서 2명만 더 구해요.',
        senderId: 'user1',
        senderName: '강남불나방',
        content: '4명이요. 지금 2명 있어서 2명만 더 구해요.',
        createdAt: now.subtract(const Duration(hours: 2, minutes: 50)),
        isMe: false,
      ),
      Message(
        id: 'mg4',
        type: MessageType.image,
        imageUrl: 'https://picsum.photos/seed/club1/400/300',
        senderId: 'user1',
        senderName: '강남불나방',
        createdAt: now.subtract(const Duration(hours: 2, minutes: 40)),
        isMe: false,
      ),
      Message(
        id: 'mg5',
        type: MessageType.text,
        text: '내일 저녁 7시에 강남역에서 만나요!',
        senderId: 'me',
        senderName: '나',
        content: '내일 저녁 7시에 강남역에서 만나요!',
        createdAt: now.subtract(const Duration(minutes: 5)),
        isMe: true,
        isRead: true,
      ),
    ],
    'room1': [
      Message(
        id: 'm1',
        type: MessageType.text,
        text: '안녕하세요! 강남 클럽 조각 같이 가실 분 구하고 있어요.',
        createdAt: now.subtract(const Duration(hours: 3)),
        isMe: false,
      ),
      Message(
        id: 'm2',
        type: MessageType.text,
        text: '네 저요! 몇 명 모이면 되나요?',
        createdAt: now.subtract(const Duration(hours: 2, minutes: 55)),
        isMe: true,
        isRead: true,
      ),
      Message(
        id: 'm3',
        type: MessageType.text,
        text: '4명이요. 지금 2명 있어서 2명만 더 구해요.',
        createdAt: now.subtract(const Duration(hours: 2, minutes: 50)),
        isMe: false,
      ),
      Message(
        id: 'm4',
        type: MessageType.image,
        imageUrl: 'https://picsum.photos/seed/club1/400/300',
        createdAt: now.subtract(const Duration(hours: 2, minutes: 35)),
        isMe: false,
      ),
      Message(
        id: 'm5',
        type: MessageType.text,
        text: '내일 저녁 7시에 강남역에서 만나요!',
        createdAt: now.subtract(const Duration(minutes: 5)),
        isMe: true,
      ),
    ],
    'room2': [
      Message(
        id: 'm11',
        type: MessageType.text,
        text: '홍대 감성주점 -> 클럽 코스 같이 가실 분!',
        createdAt: now.subtract(const Duration(hours: 5)),
        isMe: false,
      ),
      Message(
        id: 'm12',
        type: MessageType.image,
        imageUrl: 'https://picsum.photos/seed/bar1/400/300',
        createdAt: now.subtract(const Duration(hours: 2)),
        isMe: false,
      ),
      Message(
        id: 'm13',
        type: MessageType.text,
        text: '다음에 또 같이 가요!',
        createdAt: now.subtract(const Duration(hours: 1, minutes: 30)),
        isMe: false,
      ),
    ],
    'room3': [
      Message(
        id: 'm17',
        type: MessageType.text,
        text: '이태원 힙합 클럽 좋아하세요?',
        createdAt: now.subtract(const Duration(days: 1, hours: 2)),
        isMe: false,
      ),
      Message(
        id: 'm18',
        type: MessageType.text,
        text: '네! Noir Stage 가보고 싶어요',
        createdAt: now.subtract(const Duration(days: 1, hours: 1)),
        isMe: true,
      ),
      Message(
        id: 'm19',
        type: MessageType.text,
        text: '이태원 클럽 어때요?',
        createdAt: now.subtract(const Duration(days: 1)),
        isMe: false,
      ),
    ],
    'room4': [
      Message(
        id: 'm20',
        type: MessageType.text,
        text: '성수 클럽 같이 가실 분 있어요?',
        createdAt: now.subtract(const Duration(days: 2, hours: 5)),
        isMe: false,
      ),
      Message(
        id: 'm21',
        type: MessageType.text,
        text: '이번 주말에 같이 가요!',
        createdAt: now.subtract(const Duration(days: 2)),
        isMe: true,
      ),
    ],
  };
}
